project_info:
  product_name: "Puzzle & Survival Automation Bot"
  game_name: "Puzzle & Survival"
  target_regions: ["Россия", "Ближнее зарубежье"]
  target_languages: ["Русский", "Английский"]
  primary_channels: ["Telegram", "Discord"]
  company_resources: "Полные ресурсы компании-провайдера"

product_description: >
  Бот автоматизации для игры Puzzle & Survival, доступный через Telegram.
  Функциональность включает автоматический сбор ресурсов, выполнение ежедневных квестов,
  прокачку юнитов и другие рутинные задачи. Бот не является пиратским софтом,
  не взламывает игру и не предоставляет нечестных преимуществ - только автоматизирует
  монотонные процессы для экономии времени игроков.

target_audience:
  primary:
    - Игроки Puzzle & Survival из России и ближнего зарубежья
    - Русскоязычная и англоязычная аудитория
    - Игроки, ценящие время и удобство
    - Пользователи Telegram и Discord
  
  secondary:
    - Игроки других мобильных игр
    - Потенциальные клиенты для других ботов автоматизации

key_features:
  - Автоматический сбор ресурсов
  - Выполнение ежедневных квестов
  - Прокачка юнитов
  - Управление через Telegram
  - Безопасность и стабильность работы
  - Простота использования

legal_considerations:
  - Бот может нарушать правила пользовательского соглашения игры
  - Не является пиратским софтом
  - Не взламывает игру
  - Не предоставляет нечестных преимуществ
  - Риск блокировки аккаунтов пользователей

market_opportunities:
  - Большое игровое сообщество в Telegram и Discord
  - Высокая потребность в автоматизации рутинных задач
  - Лояльная игровая аудитория
  - Возможность монетизации через подписку

challenges:
  - Правовые риски использования
  - Возможные блокировки аккаунтов
  - Необходимость объяснения легальности продукта
  - Конкуренция с другими ботами
  - Технические ограничения игры

success_metrics:
  - Количество активных пользователей
  - Конверсия в платящих клиентов
  - Удержание пользователей
  - Рост сообщества в Telegram/Discord
  - Положительные отзывы и рекомендации 