research_task:
  description: >
    Проведите тщательное исследование клиента и конкурентов в контексте {customer_domain}.
    Убедитесь, что вы найдете любую интересную и актуальную информацию, учитывая,
    что текущий год - 2024. Мы работаем с ними над следующим проектом: {project_description}.
  expected_output: >
    Полный отчет о клиенте, его клиентах и конкурентах, включая их демографию,
    предпочтения, позиционирование на рынке и вовлеченность аудитории.
  output_format: 'raw'

project_understanding_task:
  description: >
    Поймите детали проекта и целевую аудиторию для {project_description}.
    Изучите предоставленные материалы и соберите дополнительную информацию при необходимости.
  expected_output: >
    Подробное резюме проекта и профиль целевой аудитории.
  output_format: 'raw'

marketing_strategy_task:
  description: >
    Сформулируйте комплексную маркетинговую стратегию для проекта {project_description}
    клиента {customer_domain}. Используйте инсайты из задачи исследования и понимания
    проекта для создания высококачественной стратегии.
  expected_output: >
    Подробный документ маркетинговой стратегии, который описывает цели, целевую аудиторию,
    ключевые сообщения и предлагаемые тактики, обязательно включите название, тактики,
    каналы и KPI.
  output_format: 'raw'

campaign_idea_task:
  description: >
    Разработайте креативные идеи маркетинговых кампаний для {project_description}.
    Убедитесь, что идеи инновационные, увлекательные и соответствуют общей
    маркетинговой стратегии.
  expected_output: >
    Список из 5 креативных идей маркетинговых кампаний с описаниями,
    целевой аудиторией и каналами.
  output_format: 'raw'

copy_creation_task:
  description: >
    Создайте маркетинговые копии на основе одобренных идей кампаний для {project_description}.
    Убедитесь, что копии убедительные, понятные и адаптированы под целевую аудиторию.
  expected_output: >
    Маркетинговые копии для каждой идеи кампании.
  output_format: 'raw'
