gaming_market_research_task:
  description: >
    Проведите комплексное исследование игрового рынка для бота автоматизации Puzzle & Survival.
    Проанализируйте целевую аудиторию в России и ближнем зарубежье, изучите конкурентов,
    особенности игрового сообщества в Telegram и Discord. Учтите правовые аспекты
    использования ботов в играх и специфику русскоязычной и англоязычной аудитории.
  expected_output: >
    Подробный анализ игрового рынка, включая профиль целевой аудитории, конкурентный анализ,
    особенности игровых сообществ, правовые риски и возможности для продвижения.
  output_format: 'raw'

gaming_audience_analysis_task:
  description: >
    Проанализируйте целевую аудиторию бота автоматизации для Puzzle & Survival.
    Изучите поведение игроков, их потребности, болевые точки и мотивацию к использованию
    автоматизации. Учтите различия между русскоязычной и англоязычной аудиторией,
    а также особенности игроков из России и ближнего зарубежья.
  expected_output: >
    Детальный профиль целевой аудитории с сегментацией по языкам, регионам,
    игровому опыту и потребностям в автоматизации.
  output_format: 'raw'

gaming_legal_risk_assessment_task:
  description: >
    Оцените правовые риски использования бота автоматизации в Puzzle & Survival.
    Проанализируйте пользовательское соглашение игры, возможные нарушения правил,
    риски блокировки аккаунтов и правовые последствия. Разработайте стратегии
    минимизации рисков и правового позиционирования продукта.
  expected_output: >
    Анализ правовых рисков, стратегии минимизации, рекомендации по позиционированию
    и правовому соответствию маркетинговых материалов.
  output_format: 'raw'

gaming_community_strategy_task:
  description: >
    Разработайте стратегию работы с игровым сообществом в Telegram и Discord.
    Создайте план создания и управления сообществами, контент-стратегию,
    методы привлечения и удержания пользователей. Учтите особенности
    русскоязычных и англоязычных игровых сообществ.
  expected_output: >
    Комплексная стратегия работы с сообществами, включая план развития каналов,
    контент-стратегию, методы модерации и вовлечения аудитории.
  output_format: 'raw'

gaming_marketing_strategy_task:
  description: >
    Создайте комплексную маркетинговую стратегию для бота автоматизации Puzzle & Survival.
    Учтите результаты анализа рынка, аудитории и правовых рисков. Разработайте
    стратегию позиционирования, каналы продвижения, контент-план и KPI.
    Фокус на русскоязычную и англоязычную аудиторию в России и ближнем зарубежье.
  expected_output: >
    Детальная маркетинговая стратегия с позиционированием, каналами продвижения,
    контент-планом, бюджетом и ключевыми показателями эффективности.
  output_format: 'raw'

gaming_content_creation_task:
  description: >
    Разработайте креативные идеи контента для продвижения бота автоматизации.
    Создайте концепции видео, постов, гайдов и рекламных материалов.
    Учтите особенности игровой аудитории, правовые ограничения и необходимость
    адаптации для русскоязычной и англоязычной аудитории.
  expected_output: >
    Портфолио креативных идей контента с описаниями, целевой аудиторией,
    каналами размещения и ожидаемым эффектом.
  output_format: 'raw'

gaming_technical_positioning_task:
  description: >
    Разработайте техническое позиционирование бота автоматизации.
    Создайте объяснения функциональности, преимуществ и безопасности продукта
    простым языком для игровой аудитории. Учтите технические ограничения
    и необходимость развеивания опасений пользователей.
  expected_output: >
    Техническое позиционирование продукта с объяснением функциональности,
    преимуществ, безопасности и ответов на частые вопросы пользователей.
  output_format: 'raw'

gaming_campaign_execution_task:
  description: >
    Создайте детальный план выполнения маркетинговой кампании для бота.
    Разработайте пошаговый план запуска, временные рамки, ресурсы и
    методы измерения эффективности. Учтите особенности игровой индустрии
    и необходимость адаптации для разных языковых аудиторий.
  expected_output: >
    Детальный план выполнения кампании с временными рамками, ресурсами,
    методами измерения и планом корректировок на основе результатов.
  output_format: 'raw' 